// dataPrefManagement.js
const dataPrefManagement = [
	{
		id: 1,
		kpiSemester: 'Semester VI',
		bulan: 'Desember',
		tahun: '2022',
		kpis: [
			{
				kpi: 'Jumlah Feature yang Dibuat / Improve',
				keterangan: 'Perbulan',
				target: '12',
				realisasi: '90',
				pencapaian: '158%',
				score: '4',
				bobot: '30%',
				hasil: '1.2',
			},
			{
				kpi: 'Penyelesaian program/project sesuai timeline',
				keterangan: '%',
				target: '100',
				realisasi: '90',
				pencapaian: '90%',
				score: '2.37',
				bobot: '25%',
				hasil: '0.59',
			},
			{
				kpi: 'Revisi Desain',
				keterangan: 'max per fitur',
				target: '2',
				realisasi: '97',
				pencapaian: '100%',
				score: '2.99',
				bobot: '25%',
				hasil: '0.75',
			},
			{
				kpi: 'Indeks Kepuasan Pelanggan Internal',
				keterangan: 'Skala 1 - 4 (Akhir Semester)',
				target: '0',
				realisasi: '99',
				pencapaian: '100%',
				score: '2.99',
				bobot: '20%',
				hasil: '0.6',
			},
		],
		score: '3.14',
	},
	{
		id: 2,
		kpiSemester: 'Semester I',
		bulan: 'Januari',
		tahun: '2022',
		kpis: [
			{
				kpi: 'Jumlah Feature yang Dibuat / Improve',
				keterangan: 'Perbulan',
				target: '12',
				realisasi: '150',
				pencapaian: '125%',
				score: '3.5',
				bobot: '30%',
				hasil: '1.05',
			},
			{
				kpi: 'Penyelesaian program/project sesuai timeline',
				keterangan: '%',
				target: '100',
				realisasi: '95',
				pencapaian: '95%',
				score: '2.5',
				bobot: '25%',
				hasil: '0.625',
			},
			{
				kpi: 'Revisi Desain',
				keterangan: 'max per fitur',
				target: '2',
				realisasi: '167',
				pencapaian: '50%',
				score: '2.0',
				bobot: '25%',
				hasil: '0.5',
			},
			{
				kpi: 'Indeks Kepuasan Pelanggan Internal',
				keterangan: 'Skala 1 - 4 (Akhir Semester)',
				target: '0',
				realisasi: '145',
				pencapaian: '100%',
				score: '2.99',
				bobot: '20%',
				hasil: '0.6',
			},
		],
		score: '2.775',
	},
	{
		id: 3,
		kpiSemester: 'Semester II',
		bulan: 'Februari',
		tahun: '2022',
		kpis: [
			{
				kpi: 'Jumlah Feature yang Dibuat / Improve',
				keterangan: 'Perbulan',
				target: '12',
				realisasi: '180',
				pencapaian: '150%',
				score: '4',
				bobot: '30%',
				hasil: '1.2',
			},
			{
				kpi: 'Penyelesaian program/project sesuai timeline',
				keterangan: '%',
				target: '100',
				realisasi: '90',
				pencapaian: '80%',
				score: '2.0',
				bobot: '25%',
				hasil: '0.5',
			},
			{
				kpi: 'Revisi Desain',
				keterangan: 'max per fitur',
				target: '2',
				realisasi: '130',
				pencapaian: '150%',
				score: '1.5',
				bobot: '25%',
				hasil: '0.375',
			},
			{
				kpi: 'Indeks Kepuasan Pelanggan Internal',
				keterangan: 'Skala 1 - 4 (Akhir Semester)',
				target: '0',
				realisasi: '100',
				pencapaian: '100%',
				score: '2.99',
				bobot: '20%',
				hasil: '0.6',
			},
		],
		score: '2.675',
	},
	{
		id: 4,
		kpiSemester: 'Semester II',
		bulan: 'Maret',
		tahun: '2022',
		kpis: [
			{
				kpi: 'Jumlah Feature yang Dibuat / Improve',
				keterangan: 'Perbulan',
				target: '12',
				realisasi: '120',
				pencapaian: '167%',
				score: '4.5',
				bobot: '30%',
				hasil: '1.35',
			},
			{
				kpi: 'Penyelesaian program/project sesuai timeline',
				keterangan: '%',
				target: '100',
				realisasi: '185',
				pencapaian: '85%',
				score: '2.125',
				bobot: '25%',
				hasil: '0.53125',
			},
			{
				kpi: 'Revisi Desain',
				keterangan: 'max per fitur',
				target: '2',
				realisasi: '120',
				pencapaian: '100%',
				score: '2.99',
				bobot: '25%',
				hasil: '0.7475',
			},
			{
				kpi: 'Indeks Kepuasan Pelanggan Internal',
				keterangan: 'Skala 1 - 4 (Akhir Semester)',
				target: '0',
				realisasi: '100',
				pencapaian: '100%',
				score: '2.99',
				bobot: '20%',
				hasil: '0.6',
			},
		],
		score: '3.22875',
	},
	{
		id: 5,
		kpiSemester: 'Semester IV',
		bulan: 'April',
		tahun: '2022',
		kpis: [
			{
				kpi: 'Jumlah Feature yang Dibuat / Improve',
				keterangan: 'Perbulan',
				target: '12',
				realisasi: '160',
				pencapaian: '133%',
				score: '4',
				bobot: '30%',
				hasil: '1.2',
			},
			{
				kpi: 'Penyelesaian program/project sesuai timeline',
				keterangan: '%',
				target: '100',
				realisasi: '100',
				pencapaian: '70%',
				score: '1.75',
				bobot: '25%',
				hasil: '0.4375',
			},
			{
				kpi: 'Revisi Desain',
				keterangan: 'max per fitur',
				target: '2',
				realisasi: '140',
				pencapaian: '200%',
				score: '1',
				bobot: '25%',
				hasil: '0.25',
			},
			{
				kpi: 'Indeks Kepuasan Pelanggan Internal',
				keterangan: 'Skala 1 - 4 (Akhir Semester)',
				target: '0',
				realisasi: '100',
				pencapaian: '100%',
				score: '2.99',
				bobot: '20%',
				hasil: '0.6',
			},
		],
		score: '2.4875',
	},
	{
		id: 6,
		kpiSemester: 'Semester V',
		bulan: 'Mei',
		tahun: '2022',
		kpis: [
			{
				kpi: 'Jumlah Feature yang Dibuat / Improve',
				keterangan: 'Perbulan',
				target: '12',
				realisasi: '170',
				pencapaian: '142%',
				score: '4',
				bobot: '30%',
				hasil: '1.2',
			},
			{
				kpi: 'Penyelesaian program/project sesuai timeline',
				keterangan: '%',
				target: '100',
				realisasi: '160',
				pencapaian: '60%',
				score: '1.5',
				bobot: '25%',
				hasil: '0.375',
			},
			{
				kpi: 'Revisi Desain',
				keterangan: 'max per fitur',
				target: '2',
				realisasi: '100',
				pencapaian: '50%',
				score: '2',
				bobot: '25%',
				hasil: '0.5',
			},
			{
				kpi: 'Indeks Kepuasan Pelanggan Internal',
				keterangan: 'Skala 1 - 4 (Akhir Semester)',
				target: '0',
				realisasi: '100',
				pencapaian: '100%',
				score: '2.99',
				bobot: '20%',
				hasil: '0.6',
			},
		],
		score: '2.675',
	},
];

module.exports = dataPrefManagement;
